// Code generated by qtc from "basic_layout.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/view/basic_layout.qtpl:1
package view

//line internal/view/basic_layout.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/view/basic_layout.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/view/basic_layout.qtpl:1
func StreamBasicLayout(qw422016 *qt422016.Writer, title string, csrfToken string, content string) {
//line internal/view/basic_layout.qtpl:1
	qw422016.N().S(`
  <!DOCTYPE html>
  <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <meta name="csrf-token" content="`)
//line internal/view/basic_layout.qtpl:7
	qw422016.E().S(csrfToken)
//line internal/view/basic_layout.qtpl:7
	qw422016.N().S(`">
      <title>`)
//line internal/view/basic_layout.qtpl:8
	qw422016.E().S(title)
//line internal/view/basic_layout.qtpl:8
	qw422016.N().S(`</title>
      <link rel="stylesheet" href="/css/style.css" type="text/css">
      <link rel="stylesheet" href="/js/app/index.css" type="text/css">
    </head>
    <body>
      `)
//line internal/view/basic_layout.qtpl:13
	qw422016.N().S(content)
//line internal/view/basic_layout.qtpl:13
	qw422016.N().S(`
      <script src="/js/app/index.js"></script>
      <script src="/js/app/index.js.map"></script>
    </body>
  </html>
`)
//line internal/view/basic_layout.qtpl:18
}

//line internal/view/basic_layout.qtpl:18
func WriteBasicLayout(qq422016 qtio422016.Writer, title string, csrfToken string, content string) {
//line internal/view/basic_layout.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/view/basic_layout.qtpl:18
	StreamBasicLayout(qw422016, title, csrfToken, content)
//line internal/view/basic_layout.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line internal/view/basic_layout.qtpl:18
}

//line internal/view/basic_layout.qtpl:18
func BasicLayout(title string, csrfToken string, content string) string {
//line internal/view/basic_layout.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/view/basic_layout.qtpl:18
	WriteBasicLayout(qb422016, title, csrfToken, content)
//line internal/view/basic_layout.qtpl:18
	qs422016 := string(qb422016.B)
//line internal/view/basic_layout.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/view/basic_layout.qtpl:18
	return qs422016
//line internal/view/basic_layout.qtpl:18
}
