// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package dbx

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Feed struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	PublicID      string
	Title         string
	Description   string
	Url           string
	LastFetchedAt pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type User struct {
	ID                uuid.UUID
	Name              string
	Username          string
	EncryptedPassword string
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}
