// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package dbx

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type User struct {
	ID                int64
	Name              string
	Username          string
	EncryptedPassword string
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}
